// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_refresh_token_from_id.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getRTFromUserID = `-- name: GetRTFromUserID :one
SELECT token FROM refresh_tokens WHERE user_id = $1
`

func (q *Queries) GetRTFromUserID(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getRTFromUserID, userID)
	var token string
	err := row.Scan(&token)
	return token, err
}
